version: 2.1
executors:
  docker-executor:
    docker:
      - image: cypress/browsers:node14.17.0-chrome91-ff89

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-{{ .Branch }}-
            - npm-v1-
            - cypress-{{ .Branch }}-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/Cypress
          key: npm-v1-{{ .Branch }}-

  test:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-{{ .Branch }}-
            - npm-v1-
            - cypress-{{ .Branch }}-
      - run: npm install
      - run: npx cypress install

  desktop-test-suite:
    executor: docker-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-{{ .Branch }}-
            - npm-v1-
            - cypress-{{ .Branch }}-
      - run: npx cypress install
      - run: npx cypress run --browser chrome --headless --spec 'cypress/e2e/testsuit.cy.js'

workflows:
  version: 2
  desktop-test-suite-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - desktop-test-suite:
          requires:
            - test
