version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.3

workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --browser chrome --env email=${email} --env password=${password} --env apiURL=${apiURL} --env baseURL=${baseURL}
          install-browsers: true
          start-command: npm run