version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:18.16.0
      - image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1 
    parallelism: 8
    steps:
      - checkout
      # - restore_cache: 
      #       key: node_modules
      - run: node --version
      - run: npm cache clean --force
      - run: npm install
      - run: npx cypress --version
      - save_cache:
          paths:
            - npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          key: 
            node_modules
      - run: npm run test:smoke-desktop-login-suite
workflows:
  version: 2.1 
  build-and-run:
    jobs:
      - build

