# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@3.1.3
# workflows:
#     example-workflow:
#       jobs:
#         - cypress/run:
#             include-branch-in-node-cache-key: false 
#             install-browsers: true 
#             package-manager: npm 
#             cypress-cache-key: custom-cypress-cache-v1-{{ arch }}-{{ checksum "package.json" }} 
#             cypress-cache-path: ~/.cache/custom-dir/Cypress 
#             cypress-command: npm run test:cypress-parallel 
#             parallelism: 5 
#             working-directory: ~/project
jobs:
  build:
    docker:
      - image: cimg/node:20.5.1 
    steps:
      - checkout
      - run: node --version
      - restore_cache: 
            key: node_modules
      - run: npm install
      - run: npx cypress --version


  install-browser:
    docker:
      - image: cypress/browsers:node14.17.0-chrome89-ff86
    steps:
      - checkout
      # Install dependencies
      - run:
          name: Install Browsers
          command: npm install
      - save_cache:
          paths:
            - npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          key: 
            node_modules

workflows:
  version: 2.1 
  build-and-run:
    jobs:
      - build
      - install-browser:
          requires:
            - build
