version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.3
  resource_class: 2xlarge,
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --browser chrome --spec 'cypress/e2e/testsuit.cy.js' 
          install-browsers: true
          start-command: npm run
      - store_artifacts:
        path: /cypress/screenshots
        destination: artifact-file