version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.3

workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: test:desktop-suite 
          install-browsers: true
          start-command: npm run 