version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-{{ .Branch }}-
            - npm-v1-
            - cypress-{{ .Branch }}-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/Cypress
          key: npm-v1-{{ .Branch }}-
  test:
    docker:
      - image: cypress/browsers:node14.17.0-chrome91-ff89
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-{{ .Branch }}-
            - npm-v1-
            - cypress-{{ .Branch }}-
      - run: npm install
      - run: npx cypress install

      # Install required libraries
      - run: sudo apt-get update && sudo apt-get install -y libnss3

  desktop-test-suite:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-{{ .Branch }}-
            - npm-v1-
            - cypress-{{ .Branch }}-
      - run: npx cypress install
      - run: npx cypress run --browser chrome --headless --spec 'cypress/e2e/testsuit.cy.js'
      - run: sudo apt-get update && sudo apt-get install -y libnss3

workflows:
  version: 2
  desktop-test-suite-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - desktop-test-suite:
          requires:
            - test
