version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:18
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v18-{{ .Branch }}-
            - npm-v18-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: npm-v18-{{ .Branch }}-
  test:
    docker:
      - image: cypress/browsers:node18.17.1-chrome91-ff89
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v18-{{ .Branch }}-
            - npm-v18-
      - run: npm install
      - run: npx cypress install
      - run : npx cypress run

workflows:
  version: 2
  smoke-test:
    jobs:
      - build
      - test:
          requires:
            - build
  