version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:18.16.0 
    resource_class: 2xlarge+
    parallelism: 8
    steps:
      - checkout
      # - restore_cache: 
      #       key: node_modules
      - run: node --version
      - run: npm cache clean --force
      - run: npm install
      - run: npx cypress --version
      - save_cache:
          paths:
            - npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          key: 
            node_modules
      - run: npx cypress run
workflows:
  version: 2.1 
  build-and-run:
    jobs:
      - build

