version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:14
    steps:
      - checkout
      - run: node --version
      - run: npm cache clean --force
      - run: npm install
      - run: npx cypress --version

  cypress-run:
    docker:
      - image: cypress/base:14
    steps:
      - checkout
      - run: npx cypress run

workflows:
  version: 2.1 
  build-and-run:
    jobs:
      - build
      - cypress-run:
          requires:
            - build
