version: 2 
jobs:
  one:
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout
      - run: echo "A first hello job"
  second:
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout
      - run: echo "A second hello job"
workflows:
  version: 2
  one_and_second:
    jobs:
      - one
      - second:
          requires:
            - one