version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.3

executors:
  win-executor:
    docker:
      - image: microsoft/windowsservercore:ltsc2019

jobs:
  windows-job:
    executor: win-executor
    steps:
      - checkout
      - run:
          name: Set up Node.js
          command: choco install nodejs-lts -y
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run Cypress Tests
          command: npm run test:cypress-parallel
      - persist_to_workspace:
          root: /home/circleci/cypress/screenshots
          path: /home/circleci/cypress/screenshots
      - store_artifacts:
          path: /home/circleci/cypress/screenshots

workflows:
  version: 2
  example-workflow:
    jobs:
      - windows-job
