version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.3
workflows:
  use-my-orb:
    jobs:
      - cypress/run:
          cypress-command: npx cypress run --browser chrome --spec 'cypress/e2e/testsuit.cy.js' 
          install-browsers: true
          start-command: npm run
          working-directory: obenan-cypress-pom/cypress # Specify the working directory here

      # Add a new job to store artifacts
      - store-screenshots:
          docker:
            - image: circleci/node:latest
          steps:
            - checkout
            - persist_to_workspace:
                root: obenan-cypress-pom/cypress # Replace with your actual repository name and cypress folder
                paths:
                  - screenshots

          
