version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout
      - run: node --version
      - run: npm install
      - run: npx cypress --version
build-run:
    docker:
      - image: cimg/node:20.5.1
    steps:
      - checkout
      - run: npx cypress run

  
    