version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/qasimnaseer-gsoftconsulting/obenan-cypress-pom/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  hello-world:

    executor: my-custom-executor
    steps:
      - checkout
      - run: npm install 
      - run : npm install cypress 
      - run : npx cypress run --browser chrome --headless --spec 'cypress/e2e/testsuit.cy.js'

workflows:
  my-custom-workflow:
    jobs:
      - hello-world