version: 2.1
jobs:
  build:
    docker:
      - image: cypress/browsers:node14.17.0-chrome89-ff86
    steps:
      - checkout
      - run: node --version
      - run: npm install
      - run: npx cypress --version

  build-run:
    docker:
      - image: cypress/browsers:node14.17.0-chrome89-ff86
    steps:
      - checkout
      - run: npx cypress run

workflows:
  version: 2.1
  build-and-run:
    jobs:
      - build
      - build-run:
          requires:
            - build
