version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.5.1 
    steps:
      - checkout
      - run: node --version
      - run: npm cache clean --force
      # - restore_cache: 
      #       key: node_modules
      - run: npm install
      - run: npx cypress --version
      - run: sudo apt-get update
      - run: sudo apt-get install xvfb
      - save_cache:
          paths:
            - npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          key: 
            node_modules
  cypress-run:
    docker:
      - image: cimg/node:20.5.1 
    steps:
      - checkout
      - restore_cache: 
            key: node_modules
      - run: Xvfb :99 #for xvfb error
      - run: export DISPLAY=:99 #for xvfb error
      - run: npx cypress run
      - run: pkill Xvfb
      - save_cache:
          paths:
            - npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          key: 
            node_modules
            
workflows:
  version: 2.1 
  build-and-run:
    jobs:
      - build
      - cypress-run:
          requires:
            - build