version: 2.1

executors:
  node:
    working_directory: ~/app
    docker:
      - image: circleci/node:12.16
  node_cypress:
    working_directory: ~/app
    docker:
      - image: cypress/base:12.16.0

jobs:
  checkout_code:
    executor: node
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - obenan-cypress-pom

  install_dependencies:
    executor: node
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - v2-deps-{{ .Branch }}-{{ checksum "package.json.lock" }}
            - v2-deps-{{ .Branch }}
            - v2-deps
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package.json.lock" }}
          paths:
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - obenan-cypress-pom/node_modules

#   run_linter:
#     executor: node
#     steps:
#       - attach_workspace:
#           at: ~/
#       - run:
#           name: Run linter
#           command: yarn lint

#   run_unit_tests:
#     executor: node
#     steps:
#       - attach_workspace:
#           at: ~/
#       - run:
#           name: Run unit tests
#           command: yarn test

#   run_cypress_tests:
#     executor: node_cypress
#     parallelism: 3
#     steps:
#       - attach_workspace:
#           at: ~/
#       - run:
#           name: Build app
#           command: yarn build
#       - run:
#           name: Run cypress tests
#           command: |
#             yarn cypress run --reporter "./dist/index.js" --spec "$(circleci tests glob "./cypress/integration/**/*.spec.js" | circleci tests split --split-by=timings | paste -sd "," -)"
#       - store_test_results:
#           path: test_results
#       - store_artifacts:
#           path: test_results

workflows:
  version: 2
  build:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
#       - run_linter:
#           requires:
#             - install_dependencies
#       - run_unit_tests:
#           requires:
#             - run_linter
      # - run_cypress_tests:
      #     requires:
      #       - run_unit_tests
# =======================================================================================

# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@3.1.3
# workflows:
#   obenan-workflow:
#     jobs:
#       - cypress/run:
#           include-branch-in-node-cache-key: false 
#           install-browsers: true 
#           package-manager: npm 
#           cypress-cache-key: custom-cypress-cache-v1-{{ arch }}-{{ checksum "package.json" }} 
#           cypress-cache-path: ~/.cache/custom-dir/Cypress 
#           cypress-command: npm run test:cypress-parallel 
#           parallelism: 5 
#           working-directory: ~/project
#           post-steps:
#             - run:
#                 name: Creating Dummy Artifacts
#                 command: |
#                   echo "my artifact file" > /tmp/artifact-1;
#                   mkdir /tmp/artifacts;
#                   echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

#             - persist_to_workspace:
#                         root: /tmp
#                         paths:
#                           - artifact-1
#                           - artifacts



# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@3.1.3
# workflows:
#     example-workflow:
#       jobs:
#         - cypress/run:
#             include-branch-in-node-cache-key: false 
#             install-browsers: true 
#             package-manager: npm 
#             cypress-cache-key: custom-cypress-cache-v1-{{ arch }}-{{ checksum "package.json" }} 
#             cypress-cache-path: ~/.cache/custom-dir/Cypress 
#             cypress-command: npm run test:cypress-parallel 
#             parallelism: 5 
#             working-directory: ~/project

# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: cypress/browsers:node-18.16.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1 
#     parallelism: 8
#     working_directory: ~/project
#     steps:
#       - checkout
#       # - restore_cache: 
#       #       key: node_modules
#       - run: node --version
#       - run: npm cache clean --force
#       - run: npm install
#       - run: npx cypress --version
#       - run: 
#           name: Prepare Package Files
#           command: |
#             TARGET_DIR="/tmp"
#             if [ -n "$HOMEDRIVE" ]; then
#               TARGET_DIR="$HOMEDRIVE\\tmp"
#             fi

#             if [ -f "package-lock.json" ]; then
#               echo "Found package-lock.json file, assuming lockfile"
#               cp package-lock.json $TARGET_DIR/node-project-lockfile
#             elif [ -f "npm-shrinkwrap.json" ]; then
#               echo "Found npm-shrinkwrap.json file, assuming lockfile"
#               cp npm-shrinkwrap.json $TARGET_DIR/node-project-lockfile
#             elif [ -f "yarn.lock" ]; then
#               echo "Found yarn.lock file, assuming lockfile"
#               cp yarn.lock $TARGET_DIR/node-project-lockfile
#             fi

#             cp package.json $TARGET_DIR/node-project-package.json
#       - save_cache:
#           paths:
#             - npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
#           key: 
#             node_modules
#       - run: npx cypress run --browser chrome --spec 'cypress/e2e/smoke/desktop/login_page/login-page-suite.cy.js'
# workflows:
#   version: 2.1 
#   build-and-run:
#     jobs:
#       - build

