version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.3

workflows:
  build:
    jobs:
      - cypress/run:
          start-command: 'npm run start'
          record: true
          parallel: true
          group: 'Cypress Tests'
          spec: 'cypress/e2e/testsuit.cy.js'