version: 2.1
orbs:
  win: circleci/windows@5.0
  cypress: cypress-io/cypress@3.1.3
executor:
  build:
    executor: win/server-2022
    steps:
      - run: Write-Host 'Hello, Windows'
workflows:
  use-my-orb:
    jobs:
      - build:
      - cypress/run:
          cypress-command: npx cypress run --browser chrome --spec 'cypress/e2e/testsuit.cy.js' 
          install-browsers: true
          start-command: npm run
